
    create table tb_usuario (
       id bigint generated by default as identity,
        cpf varchar(11) not null,
        email varchar(40) not null,
        endereco varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table tb_usuario (
       id bigint generated by default as identity,
        cpf varchar(11) not null,
        email varchar(40) not null,
        endereco varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table tb_usuario (
       id bigint generated by default as identity,
        cpf varchar(11) not null,
        email varchar(40) not null,
        endereco varchar(255),
        nome varchar(255) not null,
        telefone varchar(255) not null,
        primary key (id)
    );

    create table tb_usuario (
       id bigint generated by default as identity,
        cpf varchar(11) not null,
        email varchar(40) not null,
        endereco varchar(255),
        nome varchar(255) not null,
        telefone varchar(255) not null,
        primary key (id)
    );
